### ISSUE TITLE
Custom.js files have issues to generate md5

### ISSUE THREAD

**Issue by eknoyon** [istiyakaminsanto/md5-generator#2]
(function ($) {
    "use strict";
    document.querySelector( "textarea" ).addEventListener("keyup", function () {
        var value = document.querySelector( this ).value;
        if(value){
            document.querySelector( ".show_output" ).text( $.md5(value)).classList.add("show_output_css");
        }
    })
})(jQuery);

**Comment by istiyakaminsanto** [comment]
@eknoyon  
Thank you for your review, I'm taking care of it
